// Created by go generate; DO NOT EDIT

package panda

// Cloud was autogenerated by go generate.
type Cloud struct {
	CreatedAt       Time   `json:"created_at,omitempty" url:"created_at,omitempty"`
	ID              string `json:"id,omitempty" url:"id,omitempty"`
	Name            string `json:"name,omitempty" url:"name,omitempty"`
	S3PrivateAccess bool   `json:"s3_private_access,omitempty" url:"s3_private_access,omitempty"`
	S3VideosBucket  string `json:"s3_videos_bucket,omitempty" url:"s3_videos_bucket,omitempty"`
	URL             string `json:"url,omitempty" url:"url,omitempty"`
	UpdatedAt       Time   `json:"updated_at,omitempty" url:"updated_at,omitempty"`
}

// Encoding was autogenerated by go generate.
type Encoding struct {
	AudioBitrate      int      `json:"audio_bitrate,omitempty" url:"audio_bitrate,omitempty"`
	AudioChannels     int      `json:"audio_channels,omitempty" url:"audio_channels,omitempty"`
	AudioCodec        string   `json:"audio_codec,omitempty" url:"audio_codec,omitempty"`
	AudioSampleRate   int      `json:"audio_sample_rate,omitempty" url:"audio_sample_rate,omitempty"`
	CreatedAt         Time     `json:"created_at,omitempty" url:"created_at,omitempty"`
	Duration          int      `json:"duration,omitempty" url:"duration,omitempty"`
	EncodingProgress  float64  `json:"encoding_progress,omitempty" url:"encoding_progress,omitempty"`
	EncodingTime      float64  `json:"encoding_time,omitempty" url:"encoding_time,omitempty"`
	ErrorClass        string   `json:"error_class,omitempty" url:"error_class,omitempty"`
	ErrorMessage      string   `json:"error_message,omitempty" url:"error_message,omitempty"`
	ExternalID        string   `json:"external_id,omitempty" url:"external_id,omitempty"`
	Extname           string   `json:"extname,omitempty" url:"extname,omitempty"`
	FileSize          int64    `json:"file_size,omitempty" url:"file_size,omitempty"`
	Files             []string `json:"files,omitempty" url:"files,omitempty"`
	Fps               float64  `json:"fps,omitempty" url:"fps,omitempty"`
	Height            int      `json:"height,omitempty" url:"height,omitempty"`
	ID                string   `json:"id,omitempty" url:"id,omitempty"`
	MimeType          string   `json:"mime_type,omitempty" url:"mime_type,omitempty"`
	Path              string   `json:"path,omitempty" url:"path,omitempty"`
	ProfileID         string   `json:"profile_id,omitempty" url:"profile_id,omitempty"`
	ProfileName       string   `json:"profile_name,omitempty" url:"profile_name,omitempty"`
	StartedEncodingAt string   `json:"started_encoding_at,omitempty" url:"started_encoding_at,omitempty"`
	Status            Status   `json:"status,omitempty" url:"status,omitempty"`
	UpdatedAt         Time     `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	VideoBitrate      int      `json:"video_bitrate,omitempty" url:"video_bitrate,omitempty"`
	VideoCodec        string   `json:"video_codec,omitempty" url:"video_codec,omitempty"`
	VideoID           string   `json:"video_id,omitempty" url:"video_id,omitempty"`
	Width             int      `json:"width,omitempty" url:"width,omitempty"`
}

// EncodingRequest was autogenerated by go generate.
type EncodingRequest struct {
	Page        int    `json:"page,omitempty" url:"page,omitempty"`
	PerPage     int    `json:"per_page,omitempty" url:"per_page,omitempty"`
	ProfileID   string `json:"profile_id,omitempty" url:"profile_id,omitempty"`
	ProfileName string `json:"profile_name,omitempty" url:"profile_name,omitempty"`
	Status      Status `json:"status,omitempty" url:"status,omitempty"`
	VideoID     string `json:"video_id,omitempty" url:"video_id,omitempty"`
}

// Events was autogenerated by go generate.
type Events struct {
	EncodingCompleted bool `json:"encoding_completed,omitempty" url:"encoding_completed,omitempty"`
	EncodingProgress  bool `json:"encoding_progress,omitempty" url:"encoding_progress,omitempty"`
	VideoCreated      bool `json:"video_created,omitempty" url:"video_created,omitempty"`
	VideoEncoded      bool `json:"video_encoded,omitempty" url:"video_encoded,omitempty"`
}

// NewEncodingRequest was autogenerated by go generate.
type NewEncodingRequest struct {
	ProfileID   string `json:"profile_id,omitempty" url:"profile_id,omitempty"`
	ProfileName string `json:"profile_name,omitempty" url:"profile_name,omitempty"`
	VideoID     string `json:"video_id,omitempty" url:"video_id,omitempty"`
}

// NewProfileRequest was autogenerated by go generate.
type NewProfileRequest struct {
	AddTimestamp     bool       `json:"add_timestamp,omitempty" url:"add_timestamp,omitempty"`
	AspectMode       AspectMode `json:"aspect_mode,omitempty" url:"aspect_mode,omitempty"`
	AudioBitrate     int        `json:"audio_bitrate,omitempty" url:"audio_bitrate,omitempty"`
	AudioChannels    int        `json:"audio_channels,omitempty" url:"audio_channels,omitempty"`
	AudioSampleRate  int        `json:"audio_sample_rate,omitempty" url:"audio_sample_rate,omitempty"`
	BufferSize       int        `json:"buffer_size,omitempty" url:"buffer_size,omitempty"`
	ClipLength       string     `json:"clip_length,omitempty" url:"clip_length,omitempty"`
	ClipOffset       string     `json:"clip_offset,omitempty" url:"clip_offset,omitempty"`
	Command          string     `json:"command,omitempty" url:"command,omitempty"`
	Deinterlace      string     `json:"deinterlace,omitempty" url:"deinterlace,omitempty"`
	Encryption       bool       `json:"encryption,omitempty" url:"encryption,omitempty"`
	EncryptionIv     string     `json:"encryption_iv,omitempty" url:"encryption_iv,omitempty"`
	EncryptionKey    string     `json:"encryption_key,omitempty" url:"encryption_key,omitempty"`
	EncryptionKeyURL string     `json:"encryption_key_url,omitempty" url:"encryption_key_url,omitempty"`
	Extname          string     `json:"extname,omitempty" url:"extname,omitempty"`
	Fps              float64    `json:"fps,omitempty" url:"fps,omitempty"`
	FrameCount       int        `json:"frame_count,omitempty" url:"frame_count,omitempty"`
	FrameInterval    string     `json:"frame_interval,omitempty" url:"frame_interval,omitempty"`
	FrameOffsets     string     `json:"frame_offsets,omitempty" url:"frame_offsets,omitempty"`
	H264Crf          int        `json:"h264_crf,omitempty" url:"h264_crf,omitempty"`
	H264Level        string     `json:"h264_level,omitempty" url:"h264_level,omitempty"`
	H264Profile      string     `json:"h264_profile,omitempty" url:"h264_profile,omitempty"`
	H264Tune         string     `json:"h264_tune,omitempty" url:"h264_tune,omitempty"`
	Height           int        `json:"height,omitempty" url:"height,omitempty"`
	KeyframeInterval int        `json:"keyframe_interval,omitempty" url:"keyframe_interval,omitempty"`
	KeyframeRate     float64    `json:"Keyframe_rate,omitempty" url:"Keyframe_rate,omitempty"`
	MaxRate          int        `json:"max_rate,omitempty" url:"max_rate,omitempty"`
	Name             string     `json:"name,omitempty" url:"name,omitempty"`
	PresetName       string     `json:"preset_name,omitempty" url:"preset_name,omitempty"`
	Stack            string     `json:"stack,omitempty" url:"stack,omitempty"`
	Title            string     `json:"title,omitempty" url:"title,omitempty"`
	TwoPass          string     `json:"two_pass,omitempty" url:"two_pass,omitempty"`
	Upscale          bool       `json:"upscale,omitempty" url:"upscale,omitempty"`
	VideoBitrate     int        `json:"video_bitrate,omitempty" url:"video_bitrate,omitempty"`
	WatermarkBottom  int        `json:"watermark_bottom,omitempty" url:"watermark_bottom,omitempty"`
	WatermarkHeight  int        `json:"watermark_height,omitempty" url:"watermark_height,omitempty"`
	WatermarkLeft    int        `json:"watermark_left,omitempty" url:"watermark_left,omitempty"`
	WatermarkRight   int        `json:"watermark_right,omitempty" url:"watermark_right,omitempty"`
	WatermarkTop     int        `json:"watermark_top,omitempty" url:"watermark_top,omitempty"`
	WatermarkURL     string     `json:"watermark_url,omitempty" url:"watermark_url,omitempty"`
	WatermarkWidth   int        `json:"watermark_width,omitempty" url:"watermark_width,omitempty"`
	Width            int        `json:"width,omitempty" url:"width,omitempty"`
}

// NewVideoRequest was autogenerated by go generate.
type NewVideoRequest struct {
	PathFormat string   `json:"path_format,omitempty" url:"path_format,omitempty"`
	Payload    string   `json:"payload,omitempty" url:"payload,omitempty"`
	Profiles   []string `json:"profiles,omitempty" url:"profiles,omitempty,comma"`
}

// Notification was autogenerated by go generate.
type Notification struct {
	Delay  float64 `json:"delay,omitempty" url:"delay,omitempty"`
	Events Events  `json:"events,omitempty" url:"events,omitempty"`
	URL    string  `json:"url,omitempty" url:"url,omitempty"`
}

// Profile was autogenerated by go generate.
type Profile struct {
	AddTimestamp     bool       `json:"add_timestamp,omitempty" url:"add_timestamp,omitempty"`
	AspectMode       AspectMode `json:"aspect_mode,omitempty" url:"aspect_mode,omitempty"`
	AudioBitrate     int        `json:"audio_bitrate,omitempty" url:"audio_bitrate,omitempty"`
	AudioChannels    int        `json:"audio_channels,omitempty" url:"audio_channels,omitempty"`
	AudioSampleRate  int        `json:"audio_sample_rate,omitempty" url:"audio_sample_rate,omitempty"`
	BufferSize       int        `json:"buffer_size,omitempty" url:"buffer_size,omitempty"`
	ClipLength       string     `json:"clip_length,omitempty" url:"clip_length,omitempty"`
	ClipOffset       string     `json:"clip_offset,omitempty" url:"clip_offset,omitempty"`
	Command          string     `json:"command,omitempty" url:"command,omitempty"`
	CreatedAt        Time       `json:"created_at,omitempty" url:"created_at,omitempty"`
	Deinterlace      string     `json:"deinterlace,omitempty" url:"deinterlace,omitempty"`
	Encryption       bool       `json:"encryption,omitempty" url:"encryption,omitempty"`
	EncryptionIv     string     `json:"encryption_iv,omitempty" url:"encryption_iv,omitempty"`
	EncryptionKey    string     `json:"encryption_key,omitempty" url:"encryption_key,omitempty"`
	EncryptionKeyURL string     `json:"encryption_key_url,omitempty" url:"encryption_key_url,omitempty"`
	Extname          string     `json:"extname,omitempty" url:"extname,omitempty"`
	Fps              float64    `json:"fps,omitempty" url:"fps,omitempty"`
	FrameCount       int        `json:"frame_count,omitempty" url:"frame_count,omitempty"`
	FrameInterval    string     `json:"frame_interval,omitempty" url:"frame_interval,omitempty"`
	FrameOffsets     string     `json:"frame_offsets,omitempty" url:"frame_offsets,omitempty"`
	H264Crf          int        `json:"h264_crf,omitempty" url:"h264_crf,omitempty"`
	H264Level        string     `json:"h264_level,omitempty" url:"h264_level,omitempty"`
	H264Profile      string     `json:"h264_profile,omitempty" url:"h264_profile,omitempty"`
	H264Tune         string     `json:"h264_tune,omitempty" url:"h264_tune,omitempty"`
	Height           int        `json:"height,omitempty" url:"height,omitempty"`
	ID               string     `json:"id,omitempty" url:"id,omitempty"`
	KeyframeInterval int        `json:"keyframe_interval,omitempty" url:"keyframe_interval,omitempty"`
	KeyframeRate     float64    `json:"Keyframe_rate,omitempty" url:"Keyframe_rate,omitempty"`
	MaxRate          int        `json:"max_rate,omitempty" url:"max_rate,omitempty"`
	Name             string     `json:"name,omitempty" url:"name,omitempty"`
	PresetName       string     `json:"preset_name,omitempty" url:"preset_name,omitempty"`
	Stack            string     `json:"stack,omitempty" url:"stack,omitempty"`
	Title            string     `json:"title,omitempty" url:"title,omitempty"`
	TwoPass          string     `json:"two_pass,omitempty" url:"two_pass,omitempty"`
	UpdatedAt        Time       `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	Upscale          bool       `json:"upscale,omitempty" url:"upscale,omitempty"`
	VideoBitrate     int        `json:"video_bitrate,omitempty" url:"video_bitrate,omitempty"`
	WatermarkBottom  int        `json:"watermark_bottom,omitempty" url:"watermark_bottom,omitempty"`
	WatermarkHeight  int        `json:"watermark_height,omitempty" url:"watermark_height,omitempty"`
	WatermarkLeft    int        `json:"watermark_left,omitempty" url:"watermark_left,omitempty"`
	WatermarkRight   int        `json:"watermark_right,omitempty" url:"watermark_right,omitempty"`
	WatermarkTop     int        `json:"watermark_top,omitempty" url:"watermark_top,omitempty"`
	WatermarkURL     string     `json:"watermark_url,omitempty" url:"watermark_url,omitempty"`
	WatermarkWidth   int        `json:"watermark_width,omitempty" url:"watermark_width,omitempty"`
	Width            int        `json:"width,omitempty" url:"width,omitempty"`
}

// ProfileRequest was autogenerated by go generate.
type ProfileRequest struct {
	Expand  bool `json:"expand,omitempty" url:"expand,omitempty"`
	Page    int  `json:"page,omitempty" url:"page,omitempty"`
	PerPage int  `json:"per_page,omitempty" url:"per_page,omitempty"`
}

// Video was autogenerated by go generate.
type Video struct {
	AudioBitrate     int     `json:"audio_bitrate,omitempty" url:"audio_bitrate,omitempty"`
	AudioChannels    int     `json:"audio_channels,omitempty" url:"audio_channels,omitempty"`
	AudioCodec       string  `json:"audio_codec,omitempty" url:"audio_codec,omitempty"`
	AudioSampleRate  int     `json:"audio_sample_rate,omitempty" url:"audio_sample_rate,omitempty"`
	CreatedAt        Time    `json:"created_at,omitempty" url:"created_at,omitempty"`
	Duration         int     `json:"duration,omitempty" url:"duration,omitempty"`
	ErrorClass       string  `json:"error_class,omitempty" url:"error_class,omitempty"`
	ErrorMessage     string  `json:"error_message,omitempty" url:"error_message,omitempty"`
	Extname          string  `json:"extname,omitempty" url:"extname,omitempty"`
	FileSize         int64   `json:"file_size,omitempty" url:"file_size,omitempty"`
	Fps              float64 `json:"fps,omitempty" url:"fps,omitempty"`
	Height           int     `json:"height,omitempty" url:"height,omitempty"`
	ID               string  `json:"id,omitempty" url:"id,omitempty"`
	MimeType         string  `json:"mime_type,omitempty" url:"mime_type,omitempty"`
	OriginalFilename string  `json:"original_filename,omitempty" url:"original_filename,omitempty"`
	Path             string  `json:"path,omitempty" url:"path,omitempty"`
	Payload          string  `json:"payload,omitempty" url:"payload,omitempty"`
	SourceURL        string  `json:"source_url,omitempty" url:"source_url,omitempty"`
	Status           Status  `json:"status,omitempty" url:"status,omitempty"`
	UpdatedAt        Time    `json:"updated_at,omitempty" url:"updated_at,omitempty"`
	VideoBitrate     int     `json:"video_bitrate,omitempty" url:"video_bitrate,omitempty"`
	VideoCodec       string  `json:"video_codec,omitempty" url:"video_codec,omitempty"`
	Width            int     `json:"width,omitempty" url:"width,omitempty"`
}

// VideoRequest was autogenerated by go generate.
type VideoRequest struct {
	Page    int    `json:"page,omitempty" url:"page,omitempty"`
	PerPage int    `json:"per_page,omitempty" url:"per_page,omitempty"`
	Status  Status `json:"status,omitempty" url:"status,omitempty"`
}
